export const OrderStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  PREPARING: 'PREPARING',
  READY_FOR_PAYMENT: 'READY_FOR_PAYMENT',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED'
} as const;

export type OrderStatusType = keyof typeof OrderStatus;
